namespace TalosSoccer.Core.enumeration
{
    public enum TeamEnum
    {
        ARGENTINA,
        AUSTRALIA,
        BRAZIL,
        CANADA,
        CHINA,
        COLOMBIA,
        COSTA_RICA,
        EGYPT,
        ENGLAND,
        FRANCE,
        GERMANY,
        GUATEMALA,
        ITALY,
        IVORY_COAST,
        JAMAICA,
        JAPAN,
        MADAGASCAR,
        MEXICO,
        MOROCCO,
        NEW_ZEALAND,
        NIGERIA,
        PHILIPHINES,
        PORTUGAL,
        QATAR,
        SENEGAL,
        SOUTH_KOREA,
        SPAIN,
        TONGA,
        URUGUAY,
        USA,
        UZBEKISTAN,
        VENEZUELA
    }
}
